export const disabilityOptions = [
  { key: "hand", name: "Hand", image: "/Disabilities/BothHands.png" },
  { key: "ankle", name: "Ankle", image: "/Disabilities/Ankle.png" },
  { key: "arm", name: "Arm", image: "/Disabilities/Arm.png" },
  { key: "bothAnkles", name: "Both Ankles", image: "/Disabilities/BothAnkles.png" },
  { key: "bothArms", name: "Both Arms", image: "/Disabilities/BothArms.png" },
  { key: "bothForearms", name: "Both Forearms", image: "/Disabilities/BothForearms.png" },
  { key: "bothHands", name: "Both Hands", image: "/Disabilities/BothHands.png" },
  { key: "bothKnees", name: "Both Knees", image: "/Disabilities/BothKnees.png" },
  { key: "bothLegs", name: "Both Legs", image: "/Disabilities/BothLegs.png" },
  { key: "cva", name: "CVA", image: "/Disabilities/CVA.png" },
  { key: "forearm", name: "Forearm", image: "/Disabilities/Forearm.png" },
  { key: "knee", name: "Knee", image: "/Disabilities/Knee.png" },
  { key: "leg", name: "Leg", image: "/Disabilities/Leg.png" },
  { key: "pelvisLegsWheelchair", name: "Pelvis Legs Wheelchair", image: "/Disabilities/PelvisLegsWheelchair.png" },
  { key: "waistWheelchair", name: "Waist Wheelchair", image: "/Disabilities/WaistWheelchair.png" },
  { key: "wheelchair", name: "Wheelchair", image: "/Disabilities/Wheelchair.png" },
];
