<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260723000300 extends AbstractMigration
{
    public function getDescription(): string { return 'Create the controlled disability catalogue'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE disability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_413A5CB2989D9B62 ON disability (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_413A5CB25E237E06 ON disability (name)');
    }

    public function down(Schema $schema): void { $this->addSql('DROP TABLE disability'); }
}
