<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260806000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add privacy-safe application outcome history and notification delivery logging';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE application_outcome_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, actor_id INT NOT NULL, previous_status VARCHAR(50) DEFAULT NULL, new_status VARCHAR(50) NOT NULL, notification_status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_APPLICATION_OUTCOME_TIMELINE ON application_outcome_event (application_id, created_at)');
        $this->addSql('CREATE INDEX IDX_APPLICATION_OUTCOME_ACTOR ON application_outcome_event (actor_id)');
        $this->addSql('ALTER TABLE application_outcome_event ADD CONSTRAINT FK_APPLICATION_OUTCOME_APPLICATION FOREIGN KEY (application_id) REFERENCES job_application (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application_outcome_event ADD CONSTRAINT FK_APPLICATION_OUTCOME_ACTOR FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE application_outcome_event');
    }
}
