<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260803000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add versioned consent, verification access audit, and private-document retention metadata';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE consent_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_id INT NOT NULL, purpose VARCHAR(80) NOT NULL, policy_version VARCHAR(30) NOT NULL, details JSON NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, withdrawn_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CONSENT_CANDIDATE_PURPOSE ON consent_record (candidate_id, purpose)');
        $this->addSql('ALTER TABLE consent_record ADD CONSTRAINT FK_CONSENT_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE TABLE candidate_verification_access_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, verification_request_id INT NOT NULL, actor_id INT NOT NULL, action VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_VERIFICATION_ACCESS_REQUEST ON candidate_verification_access_event (verification_request_id)');
        $this->addSql('CREATE INDEX IDX_VERIFICATION_ACCESS_ACTOR ON candidate_verification_access_event (actor_id)');
        $this->addSql('ALTER TABLE candidate_verification_access_event ADD CONSTRAINT FK_VERIFICATION_ACCESS_REQUEST FOREIGN KEY (verification_request_id) REFERENCES candidate_verification_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_verification_access_event ADD CONSTRAINT FK_VERIFICATION_ACCESS_ACTOR FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_verification_request ALTER document_stored_name DROP NOT NULL');
        $this->addSql('ALTER TABLE candidate_verification_request ADD document_retention_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE candidate_verification_request ADD document_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql("UPDATE candidate_verification_request SET document_retention_until = reviewed_at + INTERVAL '30 days' WHERE reviewed_at IS NOT NULL");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE candidate_verification_access_event');
        $this->addSql('DROP TABLE consent_record');
        $this->addSql('ALTER TABLE candidate_verification_request DROP document_retention_until');
        $this->addSql('ALTER TABLE candidate_verification_request DROP document_deleted_at');
        $this->addSql("UPDATE candidate_verification_request SET document_stored_name = 'deleted-document' WHERE document_stored_name IS NULL");
        $this->addSql('ALTER TABLE candidate_verification_request ALTER document_stored_name SET NOT NULL');
    }
}
