<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260731000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add confirmed task skills and privacy-safe AI workflow audit events without changing scoring';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE candidate_task_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_profile_id INT NOT NULL, task_id INT NOT NULL, note TEXT DEFAULT NULL, source VARCHAR(20) DEFAULT \'manual\' NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CANDIDATE_TASK_SKILL_PROFILE ON candidate_task_skill (candidate_profile_id)');
        $this->addSql('CREATE INDEX IDX_CANDIDATE_TASK_SKILL_TASK ON candidate_task_skill (task_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_candidate_task_skill ON candidate_task_skill (candidate_profile_id, task_id)');
        $this->addSql('ALTER TABLE candidate_task_skill ADD CONSTRAINT FK_CANDIDATE_TASK_SKILL_PROFILE FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_task_skill ADD CONSTRAINT FK_CANDIDATE_TASK_SKILL_TASK FOREIGN KEY (task_id) REFERENCES job_definition_task (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE TABLE candidate_profile_ai_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_id INT NOT NULL, event_type VARCHAR(40) NOT NULL, language VARCHAR(16) NOT NULL, details JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PROFILE_AI_EVENT_CANDIDATE ON candidate_profile_ai_event (candidate_id)');
        $this->addSql('ALTER TABLE candidate_profile_ai_event ADD CONSTRAINT FK_PROFILE_AI_EVENT_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE candidate_profile_ai_event DROP CONSTRAINT FK_PROFILE_AI_EVENT_CANDIDATE');
        $this->addSql('DROP TABLE candidate_profile_ai_event');
        $this->addSql('ALTER TABLE candidate_task_skill DROP CONSTRAINT FK_CANDIDATE_TASK_SKILL_PROFILE');
        $this->addSql('ALTER TABLE candidate_task_skill DROP CONSTRAINT FK_CANDIDATE_TASK_SKILL_TASK');
        $this->addSql('DROP TABLE candidate_task_skill');
    }
}
