<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260723000400 extends AbstractMigration
{
    public function getDescription(): string { return 'Create disability-to-task feasibility assessments'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE disability_task_assessment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, disability_id INT NOT NULL, task_id INT NOT NULL, feasibility VARCHAR(30) NOT NULL, source_sheet VARCHAR(255) DEFAULT NULL, source_row INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6E498790709924E5 ON disability_task_assessment (disability_id)');
        $this->addSql('CREATE INDEX IDX_6E4987908DB60186 ON disability_task_assessment (task_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_disability_task ON disability_task_assessment (disability_id, task_id)');
        $this->addSql('ALTER TABLE disability_task_assessment ADD CONSTRAINT FK_ASSESSMENT_DISABILITY FOREIGN KEY (disability_id) REFERENCES disability (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disability_task_assessment ADD CONSTRAINT FK_ASSESSMENT_TASK FOREIGN KEY (task_id) REFERENCES job_definition_task (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("ALTER TABLE disability_task_assessment ADD CONSTRAINT CHK_ASSESSMENT_FEASIBILITY CHECK (feasibility IN ('feasible', 'needs_assistance', 'avoid'))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE disability_task_assessment DROP CONSTRAINT FK_ASSESSMENT_DISABILITY');
        $this->addSql('ALTER TABLE disability_task_assessment DROP CONSTRAINT FK_ASSESSMENT_TASK');
        $this->addSql('DROP TABLE disability_task_assessment');
    }
}
