<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add candidate opportunity preferences, position interests, and work or training opportunity type';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE candidate_profile ADD opportunity_preference VARCHAR(20) DEFAULT 'both' NOT NULL");
        $this->addSql("ALTER TABLE job_post ADD opportunity_type VARCHAR(20) DEFAULT 'work' NOT NULL");
        $this->addSql('CREATE TABLE candidate_position_interest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_profile_id INT NOT NULL, job_definition_id INT NOT NULL, knowledge_level VARCHAR(30) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF81A01DFE3D0586 ON candidate_position_interest (candidate_profile_id)');
        $this->addSql('CREATE INDEX IDX_AF81A01D7AC0F7DD ON candidate_position_interest (job_definition_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_candidate_position_interest ON candidate_position_interest (candidate_profile_id, job_definition_id)');
        $this->addSql('ALTER TABLE candidate_position_interest ADD CONSTRAINT FK_CANDIDATE_POSITION_PROFILE FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE candidate_position_interest ADD CONSTRAINT FK_CANDIDATE_POSITION_DEFINITION FOREIGN KEY (job_definition_id) REFERENCES job_definition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE candidate_position_interest');
        $this->addSql('ALTER TABLE candidate_profile DROP opportunity_preference');
        $this->addSql('ALTER TABLE job_post DROP opportunity_type');
    }
}
