<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260723000700 extends AbstractMigration
{
    public function getDescription(): string { return 'Remove legacy employer-owned jobs tasks and require catalogue jobs'; }
    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE job_task');
        $this->addSql('ALTER TABLE job_post DROP title');
        $this->addSql('ALTER TABLE job_post DROP category');
        $this->addSql('ALTER TABLE job_post DROP requirements');
        $this->addSql('ALTER TABLE job_post ALTER job_definition_id SET NOT NULL');
    }
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_post ALTER job_definition_id DROP NOT NULL');
        $this->addSql('ALTER TABLE job_post ADD title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE job_post ADD category VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE job_post ADD requirements TEXT DEFAULT NULL');
        $this->addSql('CREATE TABLE job_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_post_id INT NOT NULL, task_name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, feasibility_level VARCHAR(50) NOT NULL, required_abilities JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5B2AD64D166B4B7 ON job_task (job_post_id)');
        $this->addSql('ALTER TABLE job_task ADD CONSTRAINT FK_D5B2AD64D166B4B7 FOREIGN KEY (job_post_id) REFERENCES job_post (id) NOT DEFERRABLE');
    }
}
