<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260723000900 extends AbstractMigration
{
    public function getDescription(): string { return 'Create ordered highlighted tasks for job postings'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_post_highlighted_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_post_id INT NOT NULL, task_id INT NOT NULL, display_position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6488B3EDD166B4B7 ON job_post_highlighted_task (job_post_id)');
        $this->addSql('CREATE INDEX IDX_6488B3ED8DB60186 ON job_post_highlighted_task (task_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_post_highlighted_task ON job_post_highlighted_task (job_post_id, task_id)');
        $this->addSql('ALTER TABLE job_post_highlighted_task ADD CONSTRAINT FK_58B28D03D166B4B7 FOREIGN KEY (job_post_id) REFERENCES job_post (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_post_highlighted_task ADD CONSTRAINT FK_58B28D038DB60186 FOREIGN KEY (task_id) REFERENCES job_definition_task (id) ON DELETE CASCADE NOT DEFERRABLE');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE job_post_highlighted_task'); }
}
