<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260803000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add private disability-card verification requests for new candidate accounts';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE candidate_verification_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, candidate_id INT NOT NULL, reviewer_id INT DEFAULT NULL, document_stored_name VARCHAR(100) NOT NULL, document_original_name VARCHAR(255) NOT NULL, document_mime_type VARCHAR(100) NOT NULL, document_size INT NOT NULL, status VARCHAR(20) NOT NULL, reviewer_note TEXT DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CANDIDATE_VERIFICATION_CANDIDATE ON candidate_verification_request (candidate_id)');
        $this->addSql('CREATE INDEX IDX_CANDIDATE_VERIFICATION_REVIEWER ON candidate_verification_request (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_CANDIDATE_VERIFICATION_STATUS ON candidate_verification_request (status)');
        $this->addSql('ALTER TABLE candidate_verification_request ADD CONSTRAINT FK_CANDIDATE_VERIFICATION_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_verification_request ADD CONSTRAINT FK_CANDIDATE_VERIFICATION_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE candidate_verification_request DROP CONSTRAINT FK_CANDIDATE_VERIFICATION_CANDIDATE');
        $this->addSql('ALTER TABLE candidate_verification_request DROP CONSTRAINT FK_CANDIDATE_VERIFICATION_REVIEWER');
        $this->addSql('DROP TABLE candidate_verification_request');
    }
}
