<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260723000100 extends AbstractMigration
{
    public function getDescription(): string { return 'Create the admin-controlled job definition table'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, minimum_education_level VARCHAR(50) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_247BFC5989D9B62 ON job_definition (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_247BFC55E237E06 ON job_definition (name)');
    }

    public function down(Schema $schema): void { $this->addSql('DROP TABLE job_definition'); }
}
