<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260723000200 extends AbstractMigration
{
    public function getDescription(): string { return 'Create normalized tasks belonging to job definitions'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_definition_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_definition_id INT NOT NULL, task_key VARCHAR(255) NOT NULL, name VARCHAR(500) NOT NULL, position INT NOT NULL, weight DOUBLE PRECISION DEFAULT 1 NOT NULL, mandatory BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C5C6B9E7AC0F7DD ON job_definition_task (job_definition_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_definition_task_key ON job_definition_task (job_definition_id, task_key)');
        $this->addSql('ALTER TABLE job_definition_task ADD CONSTRAINT FK_JOB_DEFINITION_TASK_JOB FOREIGN KEY (job_definition_id) REFERENCES job_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_definition_task DROP CONSTRAINT FK_JOB_DEFINITION_TASK_JOB');
        $this->addSql('DROP TABLE job_definition_task');
    }
}
